linters:
  enable-all: true
  disable:
    - wsl
    - scopelint
    - tparallel
    - gomnd
    - gochecknoglobals
    - paralleltest
    - gochecknoinits
    - funlen
    - godot
    - godox
    - nonamedreturns
  fast: true
