name: Go

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: |
          cd ./kit
          go test -v -race -cover -covermode=atomic -coverprofile=coverage.out -count=1 \
            ./kit/... \
            ./std/gateways/fasthttp \
            ./std/gateways/fastws \
            ./std/gateways/silverhttp \
            ./std/clusters/rediscluster

      - name: Codecov KIT
        uses: codecov/codecov-action@v3.1.0
        with:
          files: ./coverage.out
          verbose: true

